### ISSUE TITLE
Bluetooth does not work

### ISSUE THREAD

**Issue by Racso09** [Zusier/Zusiers-optimization-Batch#4]

**Comment by Zusier** [comment]
Did you disable bluetooth support?

**Comment by Racso09** [comment]
> ¿Desactivaste la compatibilidad con bluetooth?

si

**Comment by Zusier** [comment]
Well thats why, please run this in command prompt and reboot just incase. It should work fine after.
`reg add "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\BTAGService" /v "Start" /t REG_DWORD /d "3" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\bthserv" /v "Start" /t REG_DWORD /d "3" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\BthAvctpSvc" /v "Start" /t REG_DWORD /d "3" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\NaturalAuthentication" /v "Start" /t REG_DWORD /d "3" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\BluetoothUserService" /v "Start" /t REG_DWORD /d "3" /f`

**Comment by Racso09** [comment]
Thanks
